#!/bin/sh

ORIG=/etc/hosts.orig
SCRIPT=/usr/bin/hostsblock-update
BLOCKLIST="http://winhelp2002.mvps.org/hosts.zip"
CRONDIR=/etc/cron.weekly/

if [ $(whoami) != "root" ]; then
	echo "You should be root to perform this command."
	exit -1
fi

if [ -f "$ORIG" ]; then
	echo "File '$ORIG' already exists. If this is a first run of $(basename $0),"
	echo "check '$ORIG' file and move/remove it."
	echo "Otherwise host-block already installed. Check $CRONDIR and $SCRIPT"
	exit -1
fi

if [ -f "$SCRIPT" ]; then
	echo "File '$SCRIPT' already exists. If this is a first run of $(basename $0),"
	echo "check '$SCRIPT' file and move/remove it."
	echo "Otherwise host-block already installed. Check $CRONDIR and $SCRIPT"
	exit -1
fi

if [ -f "$CRONDIR$SCRIPT" ]; then
	echo "File '$CRONDIR$SCRIPT' already exists. If this is a first run of $(basename $0),"
	echo "check '$CRONDIR$SCRIPT' file and move/remove it."
	echo "Otherwise host-block already installed. Check $CRONDIR and $SCRIPT"
	exit -1
fi

cp /etc/hosts $ORIG

echo "#!/bin/sh" > $SCRIPT
echo "echo \"#AUTO-GENERATED, DO NOT EDIT THIS FILE!\" > /etc/hosts" >> $SCRIPT
echo "echo \"#See $CRONDIR and $SCRIPT\" >> /etc/hosts" >> $SCRIPT
echo "cat $ORIG >> /etc/hosts" >> $SCRIPT
echo "curl -s $BLOCKLIST | zcat 2>/dev/null | grep -v ^# | grep -vw localhost >> /etc/hosts" >> $SCRIPT

chmod +x $SCRIPT
$SCRIPT

ln -s $SCRIPT $CRONDIR

if grep 'AUTO-GENERATED' /etc/hosts > /dev/null; then
	echo "Everything is OK!"
	echo "Check $CRONDIR and $SCRIPT if you want to tune it with yourself."
else
	echo "Something is wrong:("
	exit -1
fi
