#!/bin/sh

VER="1.0"
ORIG=/etc/hosts.orig
SCRIPTNAME=hostsblock-update
SCRIPT=/usr/bin/$SCRIPTNAME
CRONDIR=/etc/cron.weekly/
BLOCKLIST="http://winhelp2002.mvps.org/hosts.txt https://jansal.googlecode.com/svn/trunk/adblock/hosts"
UPDATE=0
if [ $(whoami) != "root" ]; then
	echo "You should be root to perform this command."
	exit -1
fi

if [ -f "$SCRIPT" ]; then
	if grep "^#hosts adblock " "$SCRIPT" > /dev/null; then
		UPDATE=1
	else
		echo "File '$SCRIPT' already exists. If this is a first run of $(basename $0),"
		echo "check '$SCRIPT' file and move/remove it."
		echo "Otherwise host-block already installed. Check $CRONDIR and $SCRIPT"
		exit -1
	fi
fi

if [ -f "$ORIG" -a "$UPDATE" = "0" ]; then
	echo "File '$ORIG' already exists. If this is a first run of $(basename $0),"
	echo "check '$ORIG' file and move/remove it."
	echo "Otherwise host-block already installed. Check $CRONDIR and $SCRIPT"
	exit -1
fi

if [ "$UPDATE" = "0" ]; then
	cp /etc/hosts $ORIG
fi

echo "#!/bin/sh" > $SCRIPT
echo "#hosts adblock $VER" >> $SCRIPT
echo "echo \"#AUTO-GENERATED, DO NOT EDIT THIS FILE!\" > /etc/hosts" >> $SCRIPT
echo "echo \"#See $CRONDIR and $SCRIPT\" >> /etc/hosts" >> $SCRIPT
echo "cat $ORIG >> /etc/hosts" >> $SCRIPT
echo "curl -s $BLOCKLIST | grep ^0.0.0.0 | sed -e 's/^0.0.0.0 //' -e 's/#.*//' | tr -d '\r' | tr ' ' '\n' | sort -u | awk '{if(length(s)+length(\$1)>(160-9)||cnt>9){print \"0.0.0.0 \" s;cnt=1;s=\$1}else{s=s \" \" \$1;cnt++}}END{print \"0.0.0.0 \" s}' >> /etc/hosts" >> $SCRIPT
chmod +x $SCRIPT
$SCRIPT

[ ! -f "$CRONDIR/$SCRIPTNAME" ] && ln -s $SCRIPT $CRONDIR

if grep 'AUTO-GENERATED' /etc/hosts > /dev/null; then
	echo "Everything is OK!"
	echo "Check $CRONDIR and $SCRIPT if you want to tune it with yourself."
else
	echo "Something is wrong:("
	exit -1
fi
