#!/bin/sh

VER="1.0"
ORIG=/etc/hosts.orig
SCRIPTNAME=hostsblock-update
SCRIPT=/usr/bin/$SCRIPTNAME
CRONDIR=/etc/cron.weekly/
BLOCKLIST="'http://winhelp2002.mvps.org/hosts.txt' 'https://jansal.googlecode.com/svn/trunk/adblock/hosts' 'http://hosts-file.net/.%5Cad_servers.txt' 'http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'"
UPDATE=0
if [ $(whoami) != "root" ]; then
	echo "You should be root to perform this command."
	exit -1
fi

if [ -f "$SCRIPT" ]; then
	if grep "^#hosts adblock " "$SCRIPT" > /dev/null; then
		UPDATE=1
	else
		echo "File '$SCRIPT' already exists. If this is a first run of $(basename $0),"
		echo "check '$SCRIPT' file and move/remove it."
		echo "Otherwise host-block already installed. Check $CRONDIR and $SCRIPT"
		exit -1
	fi
fi

if [ -f "$ORIG" -a "$UPDATE" = "0" ]; then
	echo "File '$ORIG' already exists. If this is a first run of $(basename $0),"
	echo "check '$ORIG' file and move/remove it."
	echo "Otherwise host-block already installed. Check $CRONDIR and $SCRIPT"
	exit -1
fi

if [ "$UPDATE" = "0" ]; then
	cp /etc/hosts $ORIG
	sed -i "1s/^/\n# AFTER EDITING YOU HAVE TO RUN THE SCRIPT: $SCRIPTNAME \!\!\!\n\n/" $ORIG
fi

echo "#!/bin/sh" > $SCRIPT
echo "#hosts adblock $VER" >> $SCRIPT
echo "if [ \$(whoami) != 'root' ]; then echo 'You should be root to perform this command.'; exit -1; fi" >> $SCRIPT
echo "echo \"#AUTO-GENERATED, DO NOT EDIT THIS FILE!\" > /etc/hosts" >> $SCRIPT
echo "echo \"#If you want to add your own rules edit $ORIG\" >> /etc/hosts" >> $SCRIPT
echo "cat $ORIG | grep -v $SCRIPTNAME >> /etc/hosts" >> $SCRIPT
# - load all lists
# - remove localhost and broadcasthost strings
# - keep only IP
# - remove IP and comments (extract hosts only)
# - remove whitespaces, one host per line
# - sort, remove duplicates
# - awk magic - optimize hosts size using aliases (max len = 160, max aliases = 9)
echo "curl -s $BLOCKLIST | grep -vw localhost\\|broadcasthost | grep ^[01] | sed -e 's/^[0127]*.0.0.[01]\\s//' -e 's/#.*//' | tr -d '\r' | tr ' \t' '\n' | grep -v ^$ | sort -u | awk 'BEGIN{z=s=\"0.0.0.0\"}{if(length(s)+length(\$1)>(160-1)||cnt>=9){print s;cnt=1;s=z \" \" \$1}else{s=s \" \" \$1;cnt++}}END{print s}' >> /etc/hosts" >> $SCRIPT
chmod +x $SCRIPT
$SCRIPT

[ ! -f "$CRONDIR/$SCRIPTNAME" ] && ln -s $SCRIPT $CRONDIR

if grep 'AUTO-GENERATED' /etc/hosts > /dev/null; then
	echo "Everything is OK!"
	echo "Check $CRONDIR and $SCRIPT if you want to tune it with yourself."
else
	echo "Something went wrong:("
	exit -1
fi
